### ISSUE TITLE
Make UI kind of similar to Stackoverflow Developer Survey page

### ISSUE THREAD

**Issue by dilumn** [stack-stats/stack-stats.github.io#10]
https://stackoverflow.com/insights/survey/2017

**Comment by janindu2r** [comment]
Please find the mockup: https://www.dropbox.com/s/0esmbjdtyb2kwlo/index-stat-stack.png?dl=0

**Comment by harshit98** [comment]
Is anyone working on it? 

@janindu2r mockup looks great!
