### ISSUE TITLE
Enhancements in the top-menu bar.

### ISSUE THREAD

**Issue by harshit98** [stack-stats/stack-stats.github.io#18]
I was going through the <a href="https://stack-stats.github.io/">Stat-Stack</a> website, and found some issues which can be enhanced much better : 

![selection_030](https://cloud.githubusercontent.com/assets/22245418/25094438/c3069684-23b4-11e7-8346-df3d849a90d8.png)

- Spelling mistake, it should be 'license' : )
-  Instead of writing 'Fork Us', we can provide a Github logo.
- Create a About Us page and Contact Us page. 
- I was going through the repo, and found that it has not been licensed. It would be better, if repo has been licensed under MIT or Apache.

**Comment by dilumn** [comment]
For the 1st & 3rd points, as I think we don't need that more button, About Us & Contact Us pages. So it's ok to remove that More button from there.

Other two are needed

**Comment by harshit98** [comment]
@dilumn ok. I'll work on this.

**Comment by harshit98** [comment]
@dilumn How to deploy it ? There are no documentations related to it!

**Comment by dilumn** [comment]
Create a pull request to master branch. After merging it will be automatically deployed. 

If you want to test while doing development, start a simple python server & access. I think you already know it.
